services:
  web:
    build: .
    # entrypoint: "./entrypoint.sh"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../app/www/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - db
  db:
    image: postgres:9.6.22-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=arch_user
      - POSTGRES_PASSWORD=arch_password
      - POSTGRES_DB=arch_db
    ports:
      - 5432:5432

volumes:
  postgres_data: